require("config.colorscheme")
require("config.options")
require("config.telescope")
require("config.treesitter")
require("config.undotree")
require("config.lspZero")
require("config.nvimTree")
require("config.lualine")
